[information]
name = "darkplus"
background = "dark"
author = 'Christian Chiarulli <chrisatmachine@gmail.com>'

[palette]
fg = '#D4D4D4'
bg = '#1E1E1E'

alt_fg = '#a4a4a4'
alt_bg = '#252525'

line = '#3e3e3e'
dark_gray = '#222222'
gray = '#808080'
context = '#606060'
light_gray = '#cccccc'

red = '#D16969'
blue = '#569CD6'
vivid_blue = '#4FC1FF'
light_blue = '#9CDCFE'
green = '#6A9955'
light_green = '#B5CEA8'
cyan = '#4EC9B0'
orange = '#CE9178'
yellow = '#DCDCAA'
yellow_orange = '#D7BA7D'
purple = '#C586C0'
magenta = '#D16D9E'

cursor_fg = '#515052'
cursor_bg = '#AEAFAD'

sign_add = '#587c0c'
sign_change = '#0c7d9d'
sign_delete = '#94151b'

sign_add_alt = '#73C991'
sign_change_alt = '#CCA700'

error = '#F44747'
warn = '#ff8800'
info = '#FFCC66'
hint = '#4bc1fe'

error_bg = '#31262d'
warn_bg = '#32302f'
info_bg = '#1e3135'
hint_bg = '#22323f'


reference = '#606060'
success_green = '#14C50B'
folder_blue = '#42A5F5'


ui_blue = '#264F78'
ui2_blue = '#042E48'
ui3_blue = '#0195F7'
ui4_blue = '#75BEFF'
ui5_blue = '#083C5A'
ui_orange = '#E8AB53'
ui2_orange = '#613214'
ui_purple = '#B180D7'

[Editor]
Normal = 'fg bg'
SignColumn = '- bg'
MsgArea = 'fg bg'
ModeMsg = 'fg alt_bg'
MsgSeparator = 'fg bg'
SpellBad = '- - c red'
SpellCap = '- - c yellow'
SpellLocal = '- - u green'
SpellRare = '- - u purple'
NormalNC = 'fg bg'
Pmenu = 'light_gray #2D2D30'
PmenuSel = '- ui2_blue'
WildMenu = 'fg ui2_blue'
CursorLineNr = 'light_gray - b'
Folded = 'gray alt_bg'
FoldColumn = 'gray alt_bg'
LineNr = 'gray -'
FloatBoder = 'gray alt_bg'
Whitespace = 'bg'
VertSplit = 'gray bg'
CursorLine = '- alt_bg'
CursorColumn = '- alt_bg'
ColorColumn = '- alt_bg'
NormalFloat = '- alt_bg'
Visual = '- ui_blue'
VisualNOS = '- alt_bg'
WarningMsg = 'error bg'
DiffText = 'alt_bg sign_delete'
DiffAdd = 'alt_bg sign_add'
DiffChange = 'alt_bg sign_change u'
DiffDelete = 'alt_bg sign_delete'
QuickFixLine = '- ui2_blue'
PmenuSbar = '- alt_bg'
PmenuThumb = '- gray'
MatchWord = '- - u'
MatchParen = 'hint - u'
MatchWordCur = '- - u'
MatchParenCur = '- - u'
Cursor = 'cursor_fg cursor_bg'
lCursor = 'cursor_fg cursor_bg'
CursorIM = 'cursor_fg cursor_bg'
TermCursor = 'cursor_fg cursor_bg'
TermCursorNC = 'cursor_fg cursor_bg'
Conceal = 'gray'
Directory = 'folder_blue'
SpecialKey = 'blue - b'
ErrorMsg = 'error bg b'
Search = '- ui5_blue'
IncSearch = '- ui2_orange'
Substitute = '- ui2_orange'
MoreMsg = 'orange'
Question = 'orange'
EndOfBuffer = 'bg'
NonText = 'bg'
TabLine = 'light_gray line'
TabLineSel = 'fg line'
TabLineFill = 'line line'

[Code]
Comment = 'green - i'
Variable = 'light_blue'
String = 'orange'
Character = 'orange'
Number = 'light_green'
Float = 'light_green'
Boolean = 'blue'
Constant = 'vivid_blue'
Type = 'cyan'
Function = 'yellow'
Keyword = 'blue'
Conditional = 'purple'
Repeat = 'purple'
Operator = 'alt_fg'
PreProc = 'purple'
Include = 'purple'
Exception = 'purple'
StorageClass = 'cyan'
Structure = 'cyan'
Typedef = 'purple'
Define = 'purple'
Macro = 'blue'
Debug = 'red'
Title = 'blue - b'
Label = 'fg'
SpecialChar = 'orange'
Delimiter = 'alt_fg'
SpecialComment = 'alt_fg'
Tag = 'blue'
Bold = '- - b'
Italic = '- - i'
Underlined = '- - u'
Ignore = 'magenta - b'
Todo = 'magenta - b'
Error = 'error - b'
Statement = 'purple'
Identifier = 'fg'
PreCondit = 'purple'
Special = 'orange'

[Treesitter]
TSComment = 'link:Comment'
TSVariable = 'link:Variable'
TSString = 'link:String'
TSStringRegex = 'link:String'
TSStringEscape = 'link:String'
TSCharacter = 'link:String'
TSCharacterSpecial = 'link:SpecialChar'
TSNumber = 'link:Number'
TSFloat = 'link:Float'
TSBoolean = 'link:Boolean'
TSConstant = 'link:Constant'
TSConstBuiltin = 'link:Constant'
TSConstructor = 'link:Type'
TSType = 'link:Type'
TSInclude = 'link:Include'
TSException = 'link:Exception'
TSKeyword = 'link:Keyword'
TSKeywordReturn = 'link:Include'
TSKeywordOperator = 'link:Keyword'
TSKeywordFunction = 'link:Keyword'
TSFunction = 'link:Function'
TSFuncBuiltin = 'link:Function'
TSMethod = 'link:Function'
TSFuncMacro = 'link:Function'
TSConditional = 'link:Conditional'
TSRepeat = 'link:Repeat'
TSOperator = 'link:Operator'
TSPreProc = 'link:PreProc'
TSStorageClass = 'link:StorageClass'
TSStructure = 'link:Structure'
TSTypeDefinition = 'link:Typedef'
TSDefine = 'link:Define'
TSNote = 'link:Comment'
TSTodo = 'link:Todo'
TSDebug = 'link:Debug'
TSDanger = 'link:Error'
TSTitle = 'link:Title'
TSLabel = 'link:Label'
TSPunctDelimiter = 'link:Delimiter'
TSTagDelimiter = 'link:Delimiter'
TSPunctBracket = 'link:Delimiter'
TSPunctSpecial = 'link:Delimiter'
TSTag = 'link:Tag'
TSStrong = 'link:Bold'
TSEmphasis = 'link:Italic'
TSUnderline = 'link:Underline'
TSStrike = '- - s'
TSStringSpecial = 'fg'
TSEnvironmentName = 'cyan'
TSVariableBuiltin = 'cyan'
TSConstMacro = 'vivid_blue'
TSTypeBuiltin = 'cyan'
TSAnnotation = 'blue'
TSNamespace = 'cyan'
TSSymbol = 'fg'
TSField = 'fg'
TSProperty = 'light_blue'
TSParameter = 'light_blue'
TSParameterReference = 'light_blue'
TSAttribute = 'light_blue'
TSText = 'alt_fg'
TSTagAttribute = 'light_blue - i'
TSError = 'error'
TSWarning = 'warn'
TSQueryLinterError = 'error'
TSURI = 'cyan - u'
TSMath = 'yellow'
TSLiteral = 'orange'

[markdown]
markdownBlockquote = 'orange'
markdownCode = 'orange'
markdownCodeBlock = 'orange'
markdownCodeDelimiter = 'orange'
markdownH1 = 'link:Title'
markdownH2 = 'link:Title'
markdownH3 = 'link:Title'
markdownH4 = 'link:Title'
markdownH5 = 'link:Title'
markdownH6 = 'link:Title'
markdownHeadingDelimiter = 'blue'
markdownHeadingRule = 'fg - b'
markdownId = 'link:Identifier'
markdownIdDeclaration = 'blue'
markdownIdDelimiter = 'light_gray'
markdownLinkDelimiter = 'light_gray'
markdownBold = 'blue - b'
markdownItalic = 'link:Italic'
markdownBoldItalic = 'yellow - bi'
markdownListMarker = 'blue'
markdownOrderedListMarker = 'purple'
markdownRule = 'gray'
markdownUrl = 'cyan - t'
markdownLinkText = 'blue'
markdownFootnote = 'orange'
markdownFootnoteDefinition = 'orange'
markdownEscape = 'yellow'

[Whichkey]
WhichKey = 'purple'
WhichKeySeperator = 'green'
WhichKeyGroup = 'blue'
WhichKeyDesc = 'fg'
WhichKeyFloat = '- alt_bg'

[Git]
SignAdd = 'sign_add'
SignChange = 'sign_change'
SignDelete = 'sign_delete'
GitSignsAdd = 'sign_add'
GitSignsChange = 'sign_change'
GitSignsDelete = 'sign_delete'

[LSP]
DiagnosticHint = 'hint'
DiagnosticInfo = 'info'
DiagnosticWarn = 'warn'
DiagnosticError = 'error'
DiagnosticOther = 'ui_purple'
DiagnosticSignHint = 'link:DiagnosticHint'
DiagnosticSignInfo = 'link:DiagnosticInfo'
DiagnosticSignWarn = 'link:DiagnosticWarn'
DiagnosticSignError = 'link:DiagnosticError'
DiagnosticSignOther = 'link:DiagnosticOther'
DiagnosticSignWarning = 'link:DiagnosticWarn'
DiagnosticFloatingHint = 'link:DiagnosticHint'
DiagnosticFloatingInfo = 'link:DiagnosticInfo'
DiagnosticFloatingWarn = 'link:DiagnosticWarn'
DiagnosticFloatingError = 'link:DiagnosticError'
DiagnosticUnderlineHint = '- - c hint'
DiagnosticUnderlineInfo = '- - c info'
DiagnosticUnderlineWarn = '- - c warn'
DiagnosticUnderlineError = '- - c error'
DiagnosticSignInformation = 'link:DiagnosticInfo'
DiagnosticVirtualTextHint = 'hint hint_bg'
DiagnosticVirtualTextInfo = 'info info_bg'
DiagnosticVirtualTextWarn = 'warn warn_bg'
DiagnosticVirtualTextError = 'error error_bg'

LspDiagnosticsError = 'error'
LspDiagnosticsWarning = 'warn'
LspDiagnosticsInfo = 'info'
LspDiagnosticsInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsHint = 'hint'
LspDiagnosticsDefaultError = 'link:LspDiagnosticsError'
LspDiagnosticsDefaultWarning = 'link:LspDiagnosticsWarning'
LspDiagnosticsDefaultInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsDefaultInfo = 'link:LspDiagnosticsInfo'
LspDiagnosticsDefaultHint = 'link:LspDiagnosticsHint'
LspDiagnosticsVirtualTextError = 'link:DiagnosticVirtualTextError'
LspDiagnosticsVirtualTextWarning = 'link:DiagnosticVirtualTextWarn'
LspDiagnosticsVirtualTextInformation = 'link:DiagnosticVirtualTextInfo'
LspDiagnosticsVirtualTextInfo = 'link:DiagnosticVirtualTextInfo'
LspDiagnosticsVirtualTextHint = 'link:DiagnosticVirtualTextHint'
LspDiagnosticsFloatingError = 'link:LspDiagnosticsError'
LspDiagnosticsFloatingWarning = 'link:LspDiagnosticsWarning'
LspDiagnosticsFloatingInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsFloatingInfo = 'link:LspDiagnosticsInfo'
LspDiagnosticsFloatingHint = 'link:LspDiagnosticsHint'
LspDiagnosticsSignError = 'link:LspDiagnosticsError'
LspDiagnosticsSignWarning = 'link:LspDiagnosticsWarning'
LspDiagnosticsSignInformation = 'link:LspDiagnosticsInfo'
LspDiagnosticsSignInfo = 'link:LspDiagnosticsInfo'
LspDiagnosticsSignHint = 'link:LspDiagnosticsHint'

NvimTreeLspDiagnosticsError = 'link:LspDiagnosticsError'
NvimTreeLspDiagnosticsWarning = 'link:LspDiagnosticsWarning'
NvimTreeLspDiagnosticsInformation = 'link:LspDiagnosticsInfo'
NvimTreeLspDiagnosticsInfo = 'link:LspDiagnosticsInfo'
NvimTreeLspDiagnosticsHint = 'link:LspDiagnosticsHint'

LspDiagnosticsUnderlineError = 'link:DiagnosticUnderlineError'
LspDiagnosticsUnderlineWarning = 'link:DiagnosticUnderlineWarn'
LspDiagnosticsUnderlineInformation = 'link:DiagnosticUnderlineInfo'
LspDiagnosticsUnderlineInfo = 'link:DiagnosticUnderlineInfo'
LspDiagnosticsUnderlineHint = 'link:DiagnosticUnderlineHint'

LspReferenceRead = '- reference'
LspReferenceText = '- reference'
LspReferenceWrite = '- reference'

LspCodeLens = 'context - i'
LspCodeLensSeparator = 'context - i'

[Quickscope]
QuickScopePrimary = '#ff007c - u'
QuickScopeSecondary = '#00dfff - u'

[Telescope]
TelescopeSelection = '- ui2_blue'
TelescopeSelectionCaret = 'red ui2_blue'
TelescopeMatching = 'yellow - bi'
TelescopeBorder = 'alt_fg'
TelescopeNormal = 'fg alt_bg'
TelescopePromptTitle = "orange"
TelescopePromptPrefix = "hint"
TelescopeResultsTitle = "orange"
TelescopePreviewTitle = "orange"
TelescopePromptCounter = "red"
TelescopePreviewHyphen = "red"

[NvimTree]
NvimTreeFolderIcon = 'link:Directory'
NvimTreeIndentMarker = 'context'
NvimTreeNormal = 'fg alt_bg'
NvimTreeVertSplit = 'alt_bg alt_bg'
NvimTreeFolderName = 'link:Directory'
NvimTreeOpenedFolderName = 'folder_blue - bi'
NvimTreeEmptyFolderName = 'gray - i'
NvimTreeGitIgnored = 'gray - i'
NvimTreeImageFile = 'light_gray'
NvimTreeSpecialFile = 'orange'
NvimTreeEndOfBuffer = 'alt_bg'
NvimTreeCursorLine = '- line'
NvimTreeGitStaged = 'sign_add_alt'
NvimTreeGitNew = 'sign_add_alt'
NvimTreeGitRenamed = 'sign_add_alt'
NvimTreeGitDeleted = 'sign_delete'
NvimTreeGitMerge = 'sign_change_alt'
NvimTreeGitDirty = 'sign_change_alt'
NvimTreeSymlink = 'cyan'
NvimTreeRootFolder = 'fg - b'
NvimTreeExecFile = '#9FBA89'

[Lir]
LirFloatNormal = 'fg alt_bg'
LirDir = 'link:Directory'
LirSymLink = 'cyan'
LirEmptyDirText = 'gray - i'

[Buffer]
BufferCurrent = 'fg bg'
BufferCurrentIndex = 'fg bg'
BufferCurrentMod = 'info bg'
BufferCurrentSign = 'hint bg'
BufferCurrentTarget = 'red bg b'

BufferVisible = 'fg bg'
BufferVisibleIndex = 'fg bg'
BufferVisibleMod = 'info bg'
BufferVisibleSign = 'gray bg'
BufferVisibleTarget = 'red bg b'

BufferInactive = 'gray alt_bg'
BufferInactiveIndex = 'gray alt_bg'
BufferInactiveMod = 'info alt_bg'
BufferInactiveSign = 'gray alt_bg'
BufferInactiveTarget = 'red alt_bg b'

[StatusLine]
StatusLine = 'context bg'
StatusLineNC = 'line bg'
StatusLineSeparator = 'line'
StatusLineTerm = 'line'
StatusLineTermNC = 'line'

[IndentBlankline]
IndentBlanklineContextChar = 'context'
IndentBlanklineContextStart = '- - u'
IndentBlanklineChar = 'dark_gray'
# IndentBlanklineSpaceCharBlankline = 'info'
# IndentBlanklineSpaceChar = 'cyan_test'

[Dashboard]
DashboardHeader = 'blue'
DashboardCenter = 'purple'
DashboardFooter = 'cyan'

[DiffView]
DiffViewNormal = 'gray alt_bg'
DiffviewStatusAdded = 'sign_add'
DiffviewStatusModified = 'sign_change'
DiffviewStatusRenamed = 'sign_change'
DiffviewStatusDeleted = 'sign_delete'
DiffviewFilePanelInsertion = 'sign_add'
DiffviewFilePanelDeletion = 'sign_delete'
DiffviewVertSplit = '- bg'

[Bookmarks]
BookmarkSign = 'sign_change'
BookmarkAnnotationSign = 'yellow'
BookmarkLine = 'ui2_blue'
BookmarkAnnotationLine = 'ui2_blue'

[Bqf]
BqfPreviewBorder = 'fg'
BqfPreviewRange = '- ui2_blue'
# BqfPreviewFloat = 'fg'
# BqfPreviewCursor = ''
# BqfSign = ''

[Cmp]
CmpItemAbbrDeprecated = 'gray - s'
CmpItemAbbrMatch = 'ui3_blue'
CmpItemAbbrMatchFuzzy = 'ui3_blue'

CmpItemKindFunction = 'blue'
CmpItemKindMethod = 'blue'
CmpItemKindConstructor = 'cyan'
CmpItemKindClass = 'cyan'
CmpItemKindEnum = 'cyan'
CmpItemKindEvent = 'yellow'
CmpItemKindInterface = 'cyan'
CmpItemKindStruct = 'cyan'
CmpItemKindVariable = 'red'
CmpItemKindField = 'red'
CmpItemKindProperty = 'red'
CmpItemKindEnumMember = 'orange'
CmpItemKindConstant = 'orange'
CmpItemKindKeyword = 'purple'
CmpItemKindModule = 'cyan'
CmpItemKindValue = 'fg'
CmpItemKindUnit = 'fg'
CmpItemKindText = 'fg'
CmpItemKindSnippet = 'yellow'
CmpItemKindFile = 'fg'
CmpItemKindFolder = 'fg'
CmpItemKindColor = 'fg'
CmpItemKindReference = 'fg'
CmpItemKindOperator = 'fg'
CmpItemKindTypeParameter = 'red'

[Navic]
NavicIconsFile = 'fg'
NavicIconsModule = 'cyan'
NavicIconsNamespace = 'fg'
NavicIconsPackage = 'fg'
NavicIconsClass = 'cyan'
NavicIconsMethod = 'blue'
NavicIconsProperty = 'red'
NavicIconsField = 'red'
NavicIconsConstructor = 'cyan'
NavicIconsEnum = 'cyan'
NavicIconsInterface = 'cyan'
NavicIconsFunction = 'blue'
NavicIconsVariable = 'red'
NavicIconsConstant = 'orange'
NavicIconsString = 'green'
NavicIconsNumber = 'orange'
NavicIconsBoolean = 'orange'
NavicIconsArray = 'cyan'
NavicIconsObject = 'cyan'
NavicIconsKey = 'purple'
NavicIconsKeyword = 'purple'
NavicIconsNull = 'orange'
NavicIconsEnumMember = 'orange'
NavicIconsStruct = 'cyan'
NavicIconsEvent = 'yellow'
NavicIconsOperator = 'fg'
NavicIconsTypeParameter = 'red'
NavicText = 'context'
NavicSeparator = 'context'

[Gps]
GpsNormal = 'gray #1d1d1d'
GpsItemKindFunction = 'ui_purple'
GpsItemKindMethod = 'ui_purple'
GpsItemKindConstructor = 'ui_orange'
GpsItemKindClass = 'ui_orange'
GpsItemKindEnum = 'ui_orange'
GpsItemKindEvent = 'ui_purple'
GpsItemKindInterface = 'fg'
GpsItemKindStruct = 'ui4_blue'
GpsItemKindVariable = 'ui4_blue'
GpsItemKindField = 'ui4_blue'
GpsItemKindProperty = 'ui4_blue'
GpsItemKindEnumMember = 'fg'
GpsItemKindConstant = 'ui4_blue'
GpsItemKindKeyword = 'fg'
GpsItemKindModule = 'fg'
GpsItemKindValue = 'fg'
GpsItemKindUnit = 'fg'
GpsItemKindText = 'fg'
GpsItemKindSnippet = 'fg'
GpsItemKindFile = 'fg'
GpsItemKindFolder = 'fg'
GpsItemKindColor = 'fg'
GpsItemKindReference = 'fg'
GpsItemKindOperator = 'fg'
GpsItemKindTypeParameter = 'fg'

[Packer]
packerString = 'ui_orange'
packerHash = 'ui4_blue'
packerOutput = 'ui_purple'
packerRelDate = 'gray'
packerSuccess = 'success_green'
packerStatusSuccess = 'ui4_blue'

[SymbolOutline]
SymbolsOutlineConnector = 'gray'
FocusedSymbol = '- #36383F'

[Notify]
NotifyERRORBorder = '#8A1F1F'
NotifyWARNBorder = '#79491D'
NotifyINFOBorder = 'ui_blue'
NotifyDEBUGBorder = 'gray'
NotifyTRACEBorder = '#4F3552'
NotifyERRORIcon = 'error'
NotifyWARNIcon = 'warn'
NotifyINFOIcon = 'ui4_blue'
NotifyDEBUGIcon = 'gray'
NotifyTRACEIcon = 'ui_purple'
NotifyERRORTitle = 'error'
NotifyWARNTitle = 'warn'
NotifyINFOTitle = 'ui4_blue'
NotifyDEBUGTitle = 'gray'
NotifyTRACETitle = 'ui_purple'
# NotifyERRORBody = Normal
# NotifyWARNBody = Normal
# NotifyINFOBody = Normal
# NotifyDEBUGBody = Normal
# NotifyTRACEBody = Normal

[TreesitterContext]
TreesitterContext = '- alt_bg'

[Hop]
HopNextKey = '#4ae0ff'
HopNextKey1 = '#d44eed'
HopNextKey2 = '#b42ecd'
HopUnmatched = 'gray'
HopPreview = '#c7ba7d'
# HopCursor = ''

[Crates]
CratesNvimLoading = 'hint'
CratesNvimVersion = 'hint'
# CratesNvimPreRelease =
# CratesNvimYanked =
# CratesNvimNoMatch =
# CratesNvimUpgrade =
# CratesNvimError =
# CratesNvimPopupPillText =
# CratesNvimPopupPillBorder =
# CratesNvimPopupDescription =
# CratesNvimPopupLabel =
# CratesNvimPopupVersion =
# CratesNvimPopupPreRelease =
# CratesNvimPopupYanked =
# CratesNvimPopupVersionDate =
# CratesNvimPopupFeature =
# CratesNvimPopupEnabled =
# CratesNvimPopupTransitive =
# CratesNvimPopupDependency =
# CratesNvimPopupOptional =
# CratesNvimPopupDependencyVersion =
# CratesNvimPopupLoading =

[Misc]
diffAdded = 'sign_add'
diffRemoved = 'sign_delete'
diffFileId = 'blue - br'
diffFile = 'alt_bg'
diffNewFile = 'green'
diffOldFile = 'red'
debugPc = '- ui5_blue'
debugBreakpoint = 'red - r'

CodiVirtualText = 'hint'
SniprunVirtualTextOk = 'hint'
SniprunFloatingWinOk = 'hint'
SniprunVirtualTextErr = 'error'
SniprunFloatingWinErr = 'error'

DapBreakpoint = 'error'

[Language]
## XML
xmlTag = 'cyan'
xmlTagName = 'cyan'

## YAML
xmlEndTag = 'cyan'
yamlPlainScalar = 'orange'
yamlTSField = 'blue'

## lua
luaFunc = 'yellow'
luaFunction = 'blue'

## hcl
hclTSPunctSpecial = 'alt_fg'

## html
htmlH1 = 'fg'
htmlH2 = 'fg'
htmlH3 = 'fg'
htmlH4 = 'fg'
htmlH5 = 'fg'
htmlH6 = 'fg'
htmlHead = 'fg'
htmlTitle = 'fg'
htmlArg = 'fg'
htmlTag = 'blue'
htmlTagN = 'blue'
htmlTagName = 'blue'
htmlComment = 'green'
htmlLink = 'orange - u'

## css
cssBraces = 'fg'
cssInclude = 'purple'
cssTagName = 'yellow'
cssClassName = 'yellow'
cssPseudoClass = 'yellow'
cssPseudoClassId = 'yellow'
cssPseudoClassLang = 'yellow'
cssIdentifier = 'yellow'
cssProp = 'fg'
cssDefinition = 'fg'
cssAttr = 'orange'
cssAttrRegion = 'orange'
cssColor = 'orange'
cssFunction = 'purple'
cssFunctionName = 'yellow'
cssVendor = 'orange'
cssValueNumber = 'orange'
cssValueLength = 'orange'
cssUnitDecorators = 'orange'
cssStyle = 'fg'
cssImportant = 'blue'

## json
jsonKeyword = 'blue'

## yaml
yamlBlockMappingKey = 'blue'

## yaml
tomlTSProperty = 'blue'
